### ISSUE TITLE
Termux support

### ISSUE THREAD

**Issue by adhilanwar** [odysseusmax/utube#1]
Hi.. can i setup virtual env on termux?...For that should i download your git as zip...(im a `noob`
![Screenshot_2019-08-12-10-59-13](https://user-images.githubusercontent.com/46475427/62846777-44906f00-bcf0-11e9-9a27-0adc5c7ce6fa.png)

**Comment by odysseusmax** [comment]
From what i see, you have setup virtual env.

**Comment by adhilanwar** [comment]
Thanks for your reply :)

**Comment by odysseusmax** [comment]
Nothing related to the bot itself, if you are really interested in knowing why, google it.
