### ISSUE TITLE
Its a feature request

### ISSUE THREAD

**Issue by adnansiddiqui-dev** [odysseusmax/utube#16]
Kindly add link download support. Because, Telegram has only 2GB file limit. Somtimes, its not possible to upload a high resolution movie in youtube. If you can add direct link download support, it would be very helpful.
I mean the bot will download from a direct download link then upload it to YouTube. I think you understood my request.😅🙏

**Comment by KHOPDIWALA** [comment]
> Kindly add link download support. Because, Telegram has only 2GB file limit. Somtimes, its not possible to upload a high resolution movie in youtube. If you can add direct link download support, it would be very helpful. I mean the bot will download from a direct download link then upload it to YouTube. I think you understood my request.😅🙏

Bro kya sachme ye bot work karta hai

**Comment by suhaib192123** [comment]
please ye private block krta hai wtt ti d
